name: Terraform

on:
  push:
    branches: main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  terraform:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.TF_AZURE_CREDENTIALS }}

      - name: Grab backend
        working-directory: terraform
        run: |
          echo '${{ secrets.TF_BACKEND }}' >> backend.vars

      - name: Unlock state container
        uses: azure/cli@v2
        with:
          azcliversion: 2.64.0
          inlineScript: |
            az storage account update \
              --resource-group "${{ secrets.TF_STATE_RG }}" \
              --name "${{ secrets.TF_STATE_STORAGE_ACCOUNT_NAME }}" \
              --default-action Allow \
              --output none && echo "[i] Waiting 30s for network ACLs to update" && sleep 30

      - name: Init
        uses: docker://hashicorp/terraform:1.15.8
        with:
          entrypoint: terraform
          args: -chdir=terraform init -backend-config=backend.vars -input=false

      - name: Set workspace
        uses: docker://hashicorp/terraform:1.15.8
        with:
          entrypoint: terraform
          args: -chdir=terraform workspace select Prod

      - name: Plan
        uses: docker://hashicorp/terraform:1.15.8
        env:
          TF_VAR_azure_client_id: ${{ secrets.TF_AZURE_CLIENT_ID }}
          TF_VAR_azure_client_secret: ${{ secrets.TF_AZURE_CLIENT_SECRET }}
        with:
          entrypoint: terraform
          args: -chdir=terraform plan -out=tfplan -input=false

      - name: Apply
        uses: docker://hashicorp/terraform:1.15.8
        env:
          TF_VAR_azure_client_id: ${{ secrets.TF_AZURE_CLIENT_ID }}
          TF_VAR_azure_client_secret: ${{ secrets.TF_AZURE_CLIENT_SECRET }}
        with:
          entrypoint: terraform
          args: -chdir=terraform apply -input=false tfplan

      - name: Lock state container
        if: always()
        uses: azure/cli@v2
        with:
          azcliversion: 2.64.0
          inlineScript: |
            az storage account update \
              --resource-group "${{ secrets.TF_STATE_RG }}" \
              --name "${{ secrets.TF_STATE_STORAGE_ACCOUNT_NAME }}" \
              --default-action Deny \
              --output none && echo "[i] Waiting 30s for network ACLs to update" && sleep 30
